### ISSUE TITLE
KOSGEB logosunun konumlandırılması

### ISSUE THREAD

**Issue by selmansancaktar** [ifenerji/webapp-seed#1]
Web sitesinin uygun bir noktasına KOSGEB logosunun eklenmesi icap etmektedir

**Comment by dbtek** [comment]
Web sayfasına ait repo maalesef bu değil, doğru repo: [ifenerji/ifenerji-web](https://github.com/ifenerji/ifenerji-web).

**Comment by dbtek** [comment]
Taşındı: [ifenerji/ifenerji-web#1](https://github.com/ifenerji/ifenerji-web/issues/1)
